version: '3.8'

services:
  api:
    container_name: API
    restart: on-failure
    build:
      context: .
      dockerfile: ./lpr.WebAPI/Dockerfile
    ports:
      - 5000:80
      - 5001:443
    depends_on:
      - db
  db:
    container_name: MariaDB
    image: mariadb:10.5.9
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: LPR
    ports:
      - 3306:3306
    volumes:
      - ./MariaDB-Data:/var/lib/mysql