version: '3.3'
services:
  
#  api:
#    container_name: API
#    restart: on-failure
#    build:
#      context: .
#      dockerfile: lpr.WebAPI/Dockerfile
#    ports:
#      - 5001:5001 
#    depends_on:
#      - db
  db:
    container_name: Database
    build: 
      context: .
      dockerfile: ./lpr.Data/Dockerfile
    ports:
      - 3306:3306
      