version: '3.8'

services:
  
  api:
    container_name: API
    build:
      context: .
      dockerfile: ./lpr.WebAPI/Dockerfile
    ports:
      - 5000:80
      - 5001:443
    depends_on:
      - db
  db:
    container_name: Database
    image: mariadb:10.5.9
    environment: 
      - MARIADB_ROOT_PASSWORD=root
    ports:
      - 6603:3306
    volumes:
      - ./MariaDB-Data:/var/lib/mysql