version: "3.8"

services:
  api:
    container_name: API
    restart: on-failure
    build:
      context: .
      dockerfile: ./lpr.WebAPI/Dockerfile
    ports:
      - 5000:80
      - 5001:443
    environment:
      - MariaDB_ConnectionString=Server=db;Database=LPR;User=root;Password=root
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;https://+:443;
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=ob6KdSAOuNB3oe7
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/dev-cert.pfx
      - S3_AccessKey=root
      - S3_PrivateKey=rootpass
    depends_on:
      - db
  db:
    container_name: Database
    image: mariadb:10.5.9
    restart: on-failure
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - ./MariaDB-Data:/var/lib/mysql
  s3:
    container_name: ObjectStorage
    restart: on-failure
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
     - MINIO_ROOT_USER=root
     - MINIO_ROOT_PASSWORD=rootpass
    ports:
     - 9000:9000
     - 9001:9001

